language: go
cache:
  directories:
    - $GOCACHE
    - $GOPATH
    - $GOPATH/pkg/mod
    - $GOPATH/github.com/golang
    - $GOPATH/gopkg.in/alecthomas
go:
  - "1.11.x"
sudo: false

before_install:
  - chmod +x ./goclean.sh

install:
  - export PATH=$PATH:$PWD/linux-amd64/
  - GO111MODULE=on go install . ./cmd/...
  - GO111MODULE=off go get -u gopkg.in/alecthomas/gometalinter.v2
  - GO111MODULE=off gometalinter.v2 --install
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./goclean.sh
